### ISSUE TITLE
Error: Failed to load plugin 'editorconfig' declared in '.eslintrc': Cannot find module './lib/rules/editorconfig'

### ISSUE THREAD

**Issue by victorperin** [phanect/eslint-plugin-editorconfig#35]
Error log:
```
> eslint .


Oops! Something went wrong! :(

ESLint: 7.15.0

Error: Failed to load plugin 'editorconfig' declared in '.eslintrc': Cannot find module './lib/rules/editorconfig'
Require stack:
- /home/perin/dev/qr-scanner-cli/node_modules/eslint-plugin-editorconfig/main.js
- /home/perin/dev/qr-scanner-cli/node_modules/@eslint/eslintrc/lib/config-array-factory.js
- /home/perin/dev/qr-scanner-cli/node_modules/@eslint/eslintrc/lib/index.js
- /home/perin/dev/qr-scanner-cli/node_modules/eslint/lib/cli-engine/cli-engine.js
- /home/perin/dev/qr-scanner-cli/node_modules/eslint/lib/eslint/eslint.js
- /home/perin/dev/qr-scanner-cli/node_modules/eslint/lib/eslint/index.js
- /home/perin/dev/qr-scanner-cli/node_modules/eslint/lib/cli.js
- /home/perin/dev/qr-scanner-cli/node_modules/eslint/bin/eslint.js
Referenced from: /home/perin/dev/qr-scanner-cli/.eslintrc
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:919:15)
    at Function.Module._load (node:internal/modules/cjs/loader:763:27)
    at Module.require (node:internal/modules/cjs/loader:991:19)
    at require (/home/perin/dev/qr-scanner-cli/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
    at Object.<anonymous> (/home/perin/dev/qr-scanner-cli/node_modules/eslint-plugin-editorconfig/main.js:5:19)
    at Module._compile (/home/perin/dev/qr-scanner-cli/node_modules/v8-compile-cache/v8-compile-cache.js:192:30)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1131:10)
    at Module.load (node:internal/modules/cjs/loader:967:32)
    at Function.Module._load (node:internal/modules/cjs/loader:807:14)
    at Module.require (node:internal/modules/cjs/loader:991:19)
```

Checked inside your project and seems that you deleted the file `'./lib/rules/editorconfig` on the last merged pull request.

**Comment by phanect** [comment]
Thanks for the reporting.
I'm working on fixing it.

**Comment by phanect** [comment]
v3.0.1 has been released and this bug should be fixed.
