### ISSUE TITLE
Incompatible with eslint-config-airbnb-base and typescript

### ISSUE THREAD

**Issue by Hesowcharov** [phanect/eslint-plugin-editorconfig#38]
Hello! Thank you for the great project!
I've met the following issue: 
```
xesoda@MacBook-Pro-Dmitry ts-eslint-editorconfig-with-airbnb % npx eslint --ext .js,.ts .

Oops! Something went wrong! :(

ESLint: 7.18.0

Error: .eslintrc.js » eslint-config-airbnb-base » /Users/xesoda/projects/ts-eslint-editorconfig-with-airbnb/node_modules/eslint-config-airbnb-base/rules/style.js:
	Configuration for rule "eol-last" is invalid:
	Value ["always"] should NOT have more than 0 items.

    at ConfigValidator.validateRuleOptions (/Users/xesoda/projects/ts-eslint-editorconfig-with-airbnb/node_modules/@eslint/eslintrc/lib/shared/config-validator.js:142:23)
    at /Users/xesoda/projects/ts-eslint-editorconfig-with-airbnb/node_modules/@eslint/eslintrc/lib/shared/config-validator.js:197:18
    at Array.forEach (<anonymous>)
    at ConfigValidator.validateRules (/Users/xesoda/projects/ts-eslint-editorconfig-with-airbnb/node_modules/@eslint/eslintrc/lib/shared/config-validator.js:194:34)
    at ConfigValidator.validateConfigArray (/Users/xesoda/projects/ts-eslint-editorconfig-with-airbnb/node_modules/@eslint/eslintrc/lib/shared/config-validator.js:320:18)
    at CascadingConfigArrayFactory._finalizeConfigArray (/Users/xesoda/projects/ts-eslint-editorconfig-with-airbnb/node_modules/@eslint/eslintrc/lib/cascading-config-array-factory.js:493:23)
    at CascadingConfigArrayFactory.getConfigArrayForFile (/Users/xesoda/projects/ts-eslint-editorconfig-with-airbnb/node_modules/@eslint/eslintrc/lib/cascading-config-array-factory.js:299:21)
    at FileEnumerator._iterateFilesRecursive (/Users/xesoda/projects/ts-eslint-editorconfig-with-airbnb/node_modules/eslint/lib/cli-engine/file-enumerator.js:440:49)
    at _iterateFilesRecursive.next (<anonymous>)
    at FileEnumerator.iterateFiles (/Users/xesoda/projects/ts-eslint-editorconfig-with-airbnb/node_modules/eslint/lib/cli-engine/file-enumerator.js:296:49)
```
for dependencies:
```
    "@typescript-eslint/eslint-plugin": "^4.14.0",
    "@typescript-eslint/parser": "^4.14.0",
    "eslint": "^7.18.0",
    "eslint-config-airbnb-base": "^14.2.1",
    "eslint-plugin-editorconfig": "^3.0.1",
    "eslint-plugin-import": "^2.22.1",
    "typescript": "^4.1.3"
```
My .eslintrc.js:
```
module.exports = {
  extends:  [
    'plugin:@typescript-eslint/recommended',
    'airbnb-base',
    'plugin:editorconfig/all',
  ],
  parser: '@typescript-eslint/parser',
  parserOptions:  {
    ecmaVersion:  2018,
    sourceType:  'module',
  },
  plugins: ['@typescript-eslint', 'editorconfig']
};
```
When I remove editorconfig plugin from the eslintrc.js, eslint starts working as expected.
Repository with details to reproduce the issue lies at https://github.com/Hesowcharov/ts-eslint-editorconfig-with-airbnb.

**Comment by phanect** [comment]
Hi @Hesowcharov, thanks for reporting.
I will take a look.

**Comment by phanect** [comment]
@Hesowcharov v3.0.2 has been released and this bug should be solved now.
Please test if it works properly on your end.

**Comment by Hesowcharov** [comment]
@phanect It works flawlessly now! Thank you very much!
